'use client'

import { useEffect, useMemo, useState } from 'react'
import { ArrowDownRight, ArrowRight, ChevronDown, ExternalLink, Globe2, Menu, Moon, Network, Plus, Sun, X } from 'lucide-react'

const sections = ['intro', 'ecosystem', 'solutions', 'services', 'industries', 'insights', 'company']
const copy = {
  en: {
    nav: ['Solutions', 'Services', 'Industries', 'Insights', 'Company'],
    heroKicker: 'THLOne / CONNECTED DIGITAL ECOSYSTEM', heroTitle: 'Connecting intelligence.\nConnecting business.', heroBody: 'THLOne brings AI, people, business systems, operations and integration together into one intelligent digital enterprise.', explore: 'Explore solutions', discover: 'Discover THLOne',
    introKicker: '01 / THE ECOSYSTEM', introTitle: 'One connected ecosystem.\nMany ways to move forward.', introBody: 'We empower organizations with integrated technologies, deep industry knowledge and long-term partnership to accelerate sustainable digital transformation.',
    solutionsKicker: '02 / SOLUTIONS', solutionsTitle: 'Technology that connects\nfrom insight to action.', servicesKicker: '03 / SERVICES', servicesTitle: 'From vision to value.', industriesKicker: '04 / INDUSTRIES', industriesTitle: 'Built around the way\nyour business moves.', insightsKicker: '05 / INSIGHTS', insightsTitle: 'Ideas for the next\nconnected enterprise.', companyKicker: '06 / COMPANY', companyTitle: 'Technology alone does not\ntransform businesses.', finalTitle: "Let's build what connects next.", talk: 'Talk to an expert', exploreAll: 'Explore all solutions', read: 'Read insight',
    products: 'Products', capabilities: 'Capabilities', serviceItems: ['Assessment & roadmap', 'Implementation & integration', 'Business process optimization', 'Support & evolve'], industries: ['Manufacturing', 'Banking', 'Retail', 'Healthcare'],
  },
  vi: {
    nav: ['Giải pháp', 'Dịch vụ', 'Ngành', 'Góc nhìn', 'Công ty'], heroKicker: 'THLONE / HỆ SINH THÁI SỐ KẾT NỐI', heroTitle: 'Kết nối trí tuệ.\nKết nối doanh nghiệp.', heroBody: 'THLOne kết nối AI, con người, hệ thống kinh doanh, vận hành và tích hợp trong một doanh nghiệp số thông minh.', explore: 'Khám phá giải pháp', discover: 'Khám phá THLOne', introKicker: '01 / HỆ SINH THÁI', introTitle: 'Một hệ sinh thái kết nối.\nNhiều cách tiến về phía trước.', introBody: 'Chúng tôi đồng hành cùng doanh nghiệp bằng công nghệ tích hợp, hiểu biết ngành sâu sắc và quan hệ hợp tác dài hạn.', solutionsKicker: '02 / GIẢI PHÁP', solutionsTitle: 'Công nghệ kết nối\ntừ insight đến hành động.', servicesKicker: '03 / DỊCH VỤ', servicesTitle: 'Từ tầm nhìn đến giá trị.', industriesKicker: '04 / NGÀNH', industriesTitle: 'Thiết kế theo cách\ndoanh nghiệp vận hành.', insightsKicker: '05 / GÓC NHÌN', insightsTitle: 'Ý tưởng cho\ndoanh nghiệp kết nối.', companyKicker: '06 / CÔNG TY', companyTitle: 'Công nghệ không tự mình\nchuyển đổi doanh nghiệp.', finalTitle: 'Cùng xây dựng kết nối tiếp theo.', talk: 'Trao đổi cùng chuyên gia', exploreAll: 'Xem tất cả giải pháp', read: 'Đọc bài viết', products: 'Sản phẩm', capabilities: 'Năng lực', serviceItems: ['Đánh giá & lộ trình', 'Triển khai & tích hợp', 'Tối ưu quy trình', 'Hỗ trợ & phát triển'], industries: ['Sản xuất', 'Ngân hàng', 'Bán lẻ', 'Y tế'],
  },
}
const solutionData = [
  ['Agentic AI', 'AI Assistant · Knowledge Base', 'Business-aware intelligence for knowledge, interaction and action.'],
  ['Digital Workplace', 'BizOne · People & HR · RPA', 'Connect people, collaboration and workflows in one workplace.'],
  ['ERP', 'SAP Business One · Odoo ERP', 'A strong foundation for finance, sales, purchasing and operations.'],
  ['Operation', 'MESOne · POSOne', 'Extend transformation into the real world of production and commerce.'],
  ['Integration Platform', 'API · IAM · Integration', 'The connective layer that makes everything work together.'],
]

const megaMenu = [
  { label: 'Solutions', vi: 'Giải pháp', items: [['Agentic AI', 'AI Assistant · Knowledge Base'], ['Digital Workplace — BizOne', 'Collaboration · People & HR · Workflow Automation'], ['ERP', 'SAP Business One · Odoo ERP'], ['Operation', 'MESOne · POSOne'], ['Integration Platform', 'API · IAM · Integration']] },
  { label: 'Services', vi: 'Dịch vụ', items: [['Digital transformation', 'Strategy, roadmap and process design'], ['Implementation', 'Systems delivery and integration'], ['Operate & evolve', 'Support, optimization and continuous improvement']] },
  { label: 'Industries', vi: 'Ngành', items: [['Manufacturing', 'Connected production and visibility'], ['Retail', 'Smarter commerce and operations'], ['Enterprise', 'Integrated business foundations']] },
  { label: 'Insights', vi: 'Góc nhìn', items: [['AI & automation', 'The next operating model'], ['Digital enterprise', 'Technology with business context'], ['Manufacturing', 'From factory signal to decision']] },
  { label: 'Company', vi: 'Công ty', items: [['About THLOne', 'One growth. One future.'], ['Vision & mission', 'Building what connects next'], ['Contact', 'Start a conversation']] },
]
function Logo() { return <a className="th-logo" href="#top" aria-label="THLOne home"><img src="https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-kt5OejVUGH9ZzRmNr0RB4f0a7T3YHC.png" alt="THLOne — One growth one future" /></a> }
function EcosystemGraphic({ active }: { active: number }) { return <div className="eco-graphic"><div className="eco-orbit orbit-a"/><div className="eco-orbit orbit-b"/><div className="eco-center">THLOne<small>CONNECTED<br/>BUSINESS</small></div>{['Agentic AI', 'People', 'ERP', 'Operations', 'Integration'].map((x, i) => <div key={x} className={`eco-pod pod-${i} ${active === i ? 'is-active' : ''}`}><span>{String(i + 1).padStart(2, '0')}</span>{x}</div>)}</div> }
function Reveal({ children, className = '' }: { children: React.ReactNode; className?: string }) { return <div className={`th-reveal ${className}`}>{children}</div> }

export default function Page() {
  const [lang, setLang] = useState<'en' | 'vi'>('en'); const [dark, setDark] = useState(true); const [menu, setMenu] = useState(false); const [openNav, setOpenNav] = useState<string | null>(null); const [active, setActive] = useState(0); const [eco, setEco] = useState(0); const t = copy[lang]
  useEffect(() => { const saved = window.localStorage.getItem('thlone-lang') as 'en' | 'vi' | null; const theme = window.localStorage.getItem('thlone-theme'); if (saved) setLang(saved); if (theme) setDark(theme === 'dark'); else setDark(window.matchMedia('(prefers-color-scheme: dark)').matches) }, [])
  useEffect(() => { document.documentElement.dataset.thloneMode = dark ? 'dark' : 'light'; document.documentElement.lang = lang; window.localStorage.setItem('thlone-theme', dark ? 'dark' : 'light'); window.localStorage.setItem('thlone-lang', lang) }, [dark, lang])
  useEffect(() => { const obs = new IntersectionObserver(es => { const top = es.filter(e => e.isIntersecting).sort((a,b) => b.intersectionRatio-a.intersectionRatio)[0]; if (top) setActive(sections.indexOf(top.target.id)) }, { rootMargin: '-35% 0px -45% 0px' }); sections.forEach(id => { const el = document.getElementById(id); if (el) obs.observe(el) }); return () => obs.disconnect() }, [])
  const activeSolution = useMemo(() => solutionData[eco], [eco])
  return <main className="th-site" id="top">
    <header className="th-nav"><Logo/><nav className="th-desktop-nav">{megaMenu.map((item, i) => <div className="th-nav-item" key={item.label}><button onClick={() => setOpenNav(openNav === item.label ? null : item.label)} aria-expanded={openNav === item.label}>{lang === 'en' ? item.label : item.vi}<ChevronDown/></button>{openNav === item.label && <div className={`th-mega-menu ${item.label === 'Solutions' ? 'solutions-menu' : ''}`}><div className="th-mega-intro"><span>THLOne</span><strong>{lang === 'en' ? item.label : item.vi}</strong><small>{item.label === 'Solutions' ? 'One connected ecosystem, many ways to move forward.' : 'Explore the thinking, capabilities and people behind connected transformation.'}</small></div><div className="th-mega-items">{item.items.map(([title, desc]) => <a key={title} href={title === 'MESOne' ? '/solutions/operation/mesone' : `#${item.label.toLowerCase()}`} onClick={() => setOpenNav(null)}><strong>{title}</strong><span>{desc}</span><ArrowRight/></a>)}</div></div>}</div>)}</nav><div className="th-nav-tools"><button className="th-lang" onClick={() => setLang(lang === 'en' ? 'vi' : 'en')} aria-label="Switch language"><span className={lang === 'en' ? 'selected' : ''}>EN</span><b>/</b><span className={lang === 'vi' ? 'selected' : ''}>VI</span></button><button className="th-icon" onClick={() => setDark(!dark)} aria-label="Toggle theme">{dark ? <Sun/> : <Moon/>}</button><a className="th-contact" href="#contact">{t.talk}<ArrowUpRightIcon/></a><button className="th-menu" onClick={() => setMenu(!menu)} aria-label="Open menu">{menu ? <X/> : <Menu/>}</button></div>{menu && <div className="th-mobile-menu">{t.nav.map((label, i) => <a key={label} href={`#${sections[i + 2]}`} onClick={() => setMenu(false)}>{label}<ArrowRight/></a>)}<a href="#contact">{t.talk}<ArrowRight/></a></div>}</header>
    <aside className="th-rail" aria-label="Page sections">{sections.map((id, i) => <button key={id} className={active === i ? 'active' : ''} onClick={() => document.getElementById(id)?.scrollIntoView({ behavior: 'smooth' })} aria-label={id}><span>{String(i + 1).padStart(2, '0')}</span></button>)}</aside>
    <section className="th-hero" id="intro"><div className="th-hero-grid"/><div className="th-hero-copy"><p className="th-kicker">{t.heroKicker}</p><h1>{t.heroTitle.split('\n').map((x, i) => <span key={x}>{x}{i === 0 && <br/>}</span>)}</h1><p className="th-lead">{t.heroBody}</p><div className="th-actions"><a className="th-btn red" href="#solutions">{t.explore}<ArrowRight/></a><a className="th-text-btn" href="#company">{t.discover}<ArrowDownRight/></a></div></div><div className="th-signal"><Network/><span>THLONE / DIGITAL TRANSFORMATION</span><strong>ONE GROWTH.<br/>ONE FUTURE.</strong><small>AI · PEOPLE · BUSINESS · OPERATIONS</small></div><div className="th-scroll">SCROLL TO EXPLORE <ArrowDownRight/></div></section>
    <section className="th-section th-intro" id="ecosystem"><Reveal><p className="th-kicker">{t.introKicker}</p><h2>{t.introTitle.split('\n').map((x,i)=><span key={x}>{x}{i===0&&<br/>}</span>)}</h2><p className="th-body">{t.introBody}</p></Reveal><div className="th-statline"><b>AI<small>INTELLIGENCE</small></b><b>PEOPLE<small>WORKPLACE</small></b><b>BUSINESS<small>ENTERPRISE SYSTEMS</small></b><b>OPERATIONS<small>CONNECTED ACTION</small></b></div><div className="th-system-visual"><img src="https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1800&q=85" alt="Abstract data center infrastructure representing THLOne digital systems and connected operations" /></div><EcosystemGraphic active={eco}/></section>
    <section className="th-section th-solutions" id="solutions"><div className="th-section-heading"><p className="th-kicker">{t.solutionsKicker}</p><h2>{t.solutionsTitle.split('\n').map((x,i)=><span key={x}>{x}{i===0&&<br/>}</span>)}</h2></div><div className="th-solution-layout"><div className="th-solution-list">{solutionData.map((s,i)=><button key={s[0]} className={eco===i?'is-active':''} onMouseEnter={() => setEco(i)} onClick={() => setEco(i)}><span>0{i+1}</span><strong>{s[0]}</strong><ArrowRight/></button>)}</div><Reveal className="th-solution-detail"><p className="th-kicker">{activeSolution[0]}</p><h3>{activeSolution[1]}</h3><p>{activeSolution[2]}</p><div className="th-detail-line"/><div className="th-detail-label">{t.products} <span>{activeSolution[1]}</span></div>{eco === 3 && <a className="th-text-btn" href="/solutions/operation/mesone">Explore MESOne <ExternalLink/></a>}</Reveal></div></section>
    <section className="th-section th-services" id="services"><div><p className="th-kicker">{t.servicesKicker}</p><h2>{t.servicesTitle}</h2></div><div className="th-service-flow">{t.serviceItems.map((x,i)=><div key={x}><span>0{i+1}</span><strong>{x}</strong><ArrowDownRight/></div>)}</div></section>
    <section className="th-section th-industries" id="industries"><div className="th-section-heading"><p className="th-kicker">{t.industriesKicker}</p><h2>{t.industriesTitle}</h2></div><div className="th-industry-grid">{t.industries.map((x,i)=><button key={x} onMouseEnter={() => setEco(i % 5)}><span>0{i+1}</span><strong>{x}</strong><ArrowUpRightIcon/></button>)}</div></section>
    <section className="th-section th-insights" id="insights"><p className="th-kicker">{t.insightsKicker}</p><h2>{t.insightsTitle}</h2><div className="th-insight-feature"><span>ARTICLE / DIGITAL TRANSFORMATION</span><h3>Building a more connected enterprise, one decision at a time.</h3><a className="th-text-btn" href="#contact">{t.read}<ArrowRight/></a></div></section>
    <section className="th-section th-company" id="company"><div><p className="th-kicker">{t.companyKicker}</p><h2>{t.companyTitle}</h2></div><div className="th-company-copy"><p>People, strategy and long-term partnership do. At THLOne, we help manufacturers embrace innovation with confidence and create sustainable business value.</p><div className="th-values"><span>Delivery is life</span><span>Quality is pride</span><span>Number is character</span></div></div></section>
    <section className="th-trust" aria-label="THLOne customers and partners"><p className="th-kicker">THLONE / CONNECTED BY TRUST</p><h2>Built with customers.<br/>Connected with partners.</h2><div className="th-logo-strip" aria-label="THLOne partners"><span className="partner-logo partner-sap">SAP <b>Business<br/>One</b><small>Partner</small></span><span className="partner-logo partner-sds">SAMSUNG SDS<small>Solution Partner</small></span><span className="partner-logo partner-nex">NEXVIONE<small>Solution Partner</small></span><span className="partner-logo partner-ws">WS₂<small>Partner</small></span><span className="partner-logo partner-odoo">odoo<small>Partner</small></span></div></section>
    <section className="th-final" id="contact"><p className="th-kicker">THLONE / LET&apos;S CONNECT</p><h2>{t.finalTitle}</h2><a className="th-btn red" href="mailto:info@thlone.vn">{t.talk}<ArrowRight/></a><div className="th-footer"><Logo/><span>+84 (0) 2822 129 589</span><span>info@thlone.vn</span><span>THU DUC, HO CHI MINH CITY</span></div></section>
  </main>
}
function ArrowUpRightIcon() { return <ArrowRight className="arrow-up"/> }
